export const DOCX_IMPORT_MAX_BYTES = 10 * 1024 * 1024;
export const DOCX_IMPORT_MAX_ENTRIES = 2_048;
export const DOCX_IMPORT_MAX_UNCOMPRESSED_BYTES = 50 * 1024 * 1024;
export const DOCX_IMPORT_MAX_ENTRY_BYTES = 20 * 1024 * 1024;
export const DOCX_IMPORT_MAX_COMPRESSION_RATIO = 200;
export const DOCX_IMPORT_MAX_HTML_CHARS = 2_000_000;

export const DOCX_IMPORT_ERROR_CODES = Object.freeze({
  INVALID_EXTENSION: "INVALID_EXTENSION",
  INVALID_MIME_TYPE: "INVALID_MIME_TYPE",
  EMPTY_FILE: "EMPTY_FILE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_SIGNATURE: "INVALID_SIGNATURE",
  ENCRYPTED_DOCUMENT: "ENCRYPTED_DOCUMENT",
  CORRUPT_DOCUMENT: "CORRUPT_DOCUMENT",
  UNSAFE_PACKAGE: "UNSAFE_PACKAGE",
  EXTERNAL_RELATIONSHIP: "EXTERNAL_RELATIONSHIP",
  UNSUPPORTED_DOCUMENT_TYPE: "UNSUPPORTED_DOCUMENT_TYPE",
  PROCESSING_LIMIT_EXCEEDED: "PROCESSING_LIMIT_EXCEEDED",
  CONVERSION_FAILED: "CONVERSION_FAILED",
});

export const DOCX_IMPORT_WARNING_CODES = Object.freeze({
  TABLES_SIMPLIFIED: "TABLES_SIMPLIFIED",
  IMAGES_DISCARDED: "IMAGES_DISCARDED",
  HEADERS_FOOTERS_DISCARDED: "HEADERS_FOOTERS_DISCARDED",
  COMMENTS_DISCARDED: "COMMENTS_DISCARDED",
  TRACK_CHANGES_SIMPLIFIED: "TRACK_CHANGES_SIMPLIFIED",
  NOTES_SIMPLIFIED: "NOTES_SIMPLIFIED",
  EQUATIONS_DISCARDED: "EQUATIONS_DISCARDED",
  FIELDS_SIMPLIFIED: "FIELDS_SIMPLIFIED",
  EMBEDDED_OBJECTS_DISCARDED: "EMBEDDED_OBJECTS_DISCARDED",
  UNSUPPORTED_STYLES_SIMPLIFIED: "UNSUPPORTED_STYLES_SIMPLIFIED",
  UNSAFE_LINKS_DISCARDED: "UNSAFE_LINKS_DISCARDED",
});

export class DocxImportError extends Error {
  constructor(code) {
    super(code);
    this.name = "DocxImportError";
    this.code = code;
  }
}
